version: '2'

services:
  emptree-server1:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    working_dir: /var/www
    ports:
      - 8080:8081
    volumes:
      - ./:/var/www/
    environment:
      PORT: 8081
      mongoUsername: admin,
      mongoPW: Test123!,
      mongoDB: employeedb
